# Generated by Django 3.0.7 on 2020-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=15)),
                ('teamid', models.IntegerField(max_length=10)),
                ('teamleader', models.CharField(max_length=15)),
            ],
        ),
    ]
