# Generated by Django 3.0.7 on 2020-06-22 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='teamleader',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='teamid',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='teamname',
        ),
        migrations.AddField(
            model_name='teams',
            name='team_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='team_member_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='team_member_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='team_member_3',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='team_member_4',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
