# Generated by Django 3.0.7 on 2020-06-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200622_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='Team',
        ),
    ]
